### PR TITLE
fix: accounts client route path

### LINKED ISSUE #64: fix accounts client request path
it's missing the `api` prefix

### PR DESCRIPTION
**Pull request by parkedwards**
resolves https://github.com/PrefectHQ/terraform-provider-prefect/issues/64

```hcl
data "prefect_account" "my_account" {
  id = "<account ID>"
}

output "debug" {
  value = {
    account = data.prefect_account.my_account
  }
}
```

```
Changes to Outputs:
  + debug = {
      + account = {
          + allow_public_workspaces = null
          + billing_email           = null
          + created                 = "2022-07-11T18:20:42Z"
          + handle                  = "<handle>"
          + id                      = "<account ID>"
          + link                    = null
          + location                = null
          + name                    = "My Account"
          + updated                 = "2023-06-01T21:47:17Z"
        }
    }
```

### CODE REVIEW

File: internal/client/accounts.go [hunk 1]
```diff
@@ -15,25 +15,26 @@ var _ = api.AccountsClient(&AccountsClient{})
...
-		apiKey:   c.apiKey,
+		hc:          c.hc,
+		apiKey:      c.apiKey,
+		routePrefix: fmt.Sprintf("%s/api/accounts", c.endpoint),
 	}, nil
 }
 
 // Get returns details for an account by ID.
 func (c *AccountsClient) Get(ctx context.Context, accountID uuid.UUID) (*api.AccountResponse, error) {
-	req, err := http.NewRequestWithContext(ctx, http.MethodGet, c.endpoint+"/accounts/"+accountID.String(), http.NoBody)
```
Comment (parkedwards) [inline internal/client/accounts.go:36]: also, repeated use of the `/accounts/` string was making golangci-lint complain

**Review by jamiezieziula — APPROVED** [review]
