### PR TITLE
fix(deployments): refactor pull step payload structure

### LINKED ISSUE #321: Flow run crashed with ValueError: Step has unexpected additional keys: branch, repository, access_token
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
Terraform v1.10.2 
on linux_amd64 
+ provider registry.terraform.io/hashicorp/aws v5.80.0 
+ provider registry.terraform.io/prefecthq/prefect v2.12.0 

### Affected Resource(s)
Prefect deployment

### Terraform Configuration Files
```tf
resource "prefect_flow" "flow" {
  name         = "flow-test"
  workspace_id = var.prefect_workspace_id
  tags         = ["test-flow"]
}

resource "prefect_deployment" "deployment" {
  name                     = "test-deployment"
  description              = "test deployment"
  workspace_id            = var.prefect_workspace_id
  flow_id                  = prefect_flow.flow.id
  entrypoint               = "flows/flow.py:my-flow"
  tags                     = ["test", "dev"]
  enforce_parameter_schema = false  
  
parameters = jsonencode({
    "parameters_uri" : "s3-path",
    "chunk_size" : 5000
  })
  
  parameter_openapi_schema = jsonencode({
    "type" : "object",
    "properties" : {
      "parameters_uri" : { "type" : "string" }
      "chunk_size"     : { "type" : "integer" }
    }
  })

  path                = "/flows"
  paused              = false
  pull_steps = [
  {
      type         = "git_clone"
      repository   = "https://my-git-repo.git"
      branch       = "main"
      access_token = var.github_token
  }
  ]
  version             = "v1.1.1"
  work_pool_name      = var.work_pool_name
  work_queue_name     = "default"
}
```

### Debug Output

Flow could not be retrieved from deployment.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/steps/core.py", line 160, in run_steps
    step_output = await run_step(step, upstream_outputs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/steps/core.py", line 116, in run_step
    raise ValueError(
_ValueError: Step has unexpected additional keys: branch, repository, access_token_

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 437, in retrieve_flow_then_begin_flow_run
    else await load_flow_from_flow_run(
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/deployments.py", line 307, in load_flow_from_flow_run
    output = await run_steps(deployment.pull_steps)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/steps/core.py", line 188, in run_steps
    raise StepExecutionError(f"Encountered error while running {fqn}") from exc
prefect.deployments.steps.core.StepExecutionError: Encountered error while running access_token
```

### Expected Behavior
The flow run should run without a crash or failure.

### Actual Behavior
The flow is crashing with `ValueError: Step has unexpected additional keys: branch, repository, access_token`. It is failing the pull_steps, is there anything that needs to be added to pull_steps? The documentation has only four fields to pull the flow code in the pull_steps that is type, branch, repository, and access_token [https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/deployment#type-1](https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/deployment#type-1)

### Steps to Reproduce
1. `terraform apply`
2. Run flow from the Prefect UI

### PR DESCRIPTION
**Pull request by mitchnielsen**
## Summary

Pull steps have a specific format in the API payload
that isn't very clearly defined by the API docs, since
the payload value is an empty list.

Looking more at the source code and documentation,
I adjusted the payload sent to the API to match the
expected format.

The format of the Terraform resource stays the same.

For reference, the incorrect format we had was:

```json
[
  {
    "type": "git_clone",
    "branch": "main",
    "repository": "https://my-git-repo.git",
    "access_token": "fake-token"
  }
]
```

The correct format is:

```json
[
  {
    "prefect.deployments.steps.git_clone": {
      "branch": "main",
      "repository": "https://my-git-repo.git",
      "access_token": "fake-token"
    }
  }
]
```

Overall changes:
* Introduced PullStepCommon to encapsulate shared fields across pull step types.
* Created specific types for PullStepGitClone, PullStepSetWorkingDirectory, and PullStepPullFrom to improve clarity and maintainability. This is where we can define the correct JSON field name for the payload.
* Updated the mapping functions to accommodate the new structure, ensuring proper handling of pull steps in both API and Terraform contexts.
* Also added `IncludeSubmodules` field, which I missed on the first pass

Closes https://github.com/PrefectHQ/terraform-provider-prefect/issues/321

### Acceptance tests

Check out the acceptance tests added in the PR.

### Manual tests

Also manually tested this to validate #321 is addressed:

1. Deployed the configuration from #321.
2. Confirmed the Deployment shows the correct Pull Step configuration:

    image

3. Clicked "Quick run" and confirmed that the flow ran successfully after cloning the repository per the pull steps:

    image

### CODE REVIEW

File: internal/provider/resources/deployment.go [hunk 1]
```diff
@@ -432,16 +444,43 @@ func mapPullStepsTerraformToAPI(tfPullSteps []PullStepModel) ([]api.PullStep, di
...
+		var apiPullStep api.PullStep
+		switch tfPullStep.Type.ValueString() {
+		case "git_clone":
+			apiPullStep.PullStepGitClone = &api.PullStepGitClone{
+				PullStepCommon:    pullStepCommon,
+				Repository:        tfPullStep.Repository.ValueStringPointer(),
+				Branch:            tfPullStep.Branch.ValueStringPointer(),
+				AccessToken:       tfPullStep.AccessToken.ValueStringPointer(),
+				IncludeSubmodules: tfPullStep.IncludeSubmodules.ValueBoolPointer(),
+			}
```
Comment (mitchnielsen) [inline internal/provider/resources/deployment.go:469]: This is obviously lengthier than the logic we defined before, but because of the payload expected by the API, I have to put configuration under certain fields in the parent struct so that I can give that parent struct the correct JSON struct tag like `prefect.deployments.steps.git_clone`.

File: internal/provider/resources/deployment.go [hunk 2]
```diff
@@ -924,15 +1007,29 @@ func (r *DeploymentResource) ImportState(ctx context.Context, req resource.Impor
 // be more concise when defining the conflicting attributes. Defining them in
 // ConfigValidators instead would be much more verbose, and disconnected from
 // the source of truth.
-func validatorsForConflictingAttributes(attributes []string) []validator.String {
+func pathExpressionsForAttributes(attributes []string) []path.Expression {
```
Comment (mitchnielsen) [inline internal/provider/resources/deployment.go:1010]: Refactored this slightly - it was set up to always return string validators, but now that we have IncludeSubmodules, we need bool validators as well. So I abstracted this one to return only path expressions, then two small helpers below that wrap this function and return the desired validator type.

File: internal/provider/resources/deployment_test.go [hunk 3]
```diff
@@ -101,33 +101,80 @@ resource "prefect_deployment" "{{.DeploymentName}}" {
 	work_queue_name = "{{.WorkQueueName}}"
 	parameter_openapi_schema = jsonencode({{.ParameterOpenAPISchema}})
 	pull_steps = [
-		{{range .PullSteps}}
+	  {{range .PullSteps}}
```
Comment (mitchnielsen) [inline internal/provider/resources/deployment_test.go:104]: The changes below are a bit hard to read, and repetitive. I tried importing `masterminds/sprig` to give us `coalesce` and some other helpers, but it started escaping quotations and I couldn't find any reference as to why that was happening. I ditched that to stick with the standard library's `template` and use `or`, which seemed to work fine at giving me a context based on which field wasn't empty - but then I was getting errors that it couldn't access nested fields when they were undefined.

This may actually be doable, but to get this PR rolling I just added a little duplication for the common fields and moved on.

File: internal/provider/resources/deployment_test.go [hunk 4]
```diff
@@ -380,7 +436,7 @@ func testAccCheckDeploymentValues(fetchedDeployment *api.Deployment, expectedVal
 		}
 
 		if !reflect.DeepEqual(fetchedDeployment.PullSteps, expectedValues.pullSteps) {
-			return fmt.Errorf("Expected pull steps to be %v, got %v", expectedValues.pullSteps, fetchedDeployment.PullSteps)
+			return fmt.Errorf("Expected pull steps to be: \n%v\n got \n%v", expectedValues.pullSteps, fetchedDeployment.PullSteps)
```
Comment (mitchnielsen) [inline internal/provider/resources/deployment_test.go:439]: Non-critical change, but made it much easier to read what the difference was between the two objects.

**Review by parkedwards — APPROVED** [review]
damn, gnarly data structure to model in TF

**Comment by mitchnielsen** [comment]
True, seems easier than Automations though :p
