### PR TITLE
fix(work pools): fix work pool base job template "inconsistent values"

### LINKED ISSUE #244: Inconsistent result after apply bug with prefect_work_pool
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

```
Terraform v1.8.5
on linux_amd64
```

Provider version 2.1.0

### Affected Resource(s)

* prefect_work_pool

### Terraform Configuration Files

```tf
resource "prefect_work_pool" "sandbox_prefect2_ecs" {
  name         = var.prefect_work_pool_name
  type         = "ecs"
  paused       = false
  workspace_id = var.prefect_config["prefect_workspace_id"] 

  base_job_template = templatefile(
    "${path.module}/templates/ecs-job-template.tftpl",
    {
        vpc_id = var.vpc_id
        default_subnets = jsonencode(var.subnets)
        ecs_cluster = aws_ecs_cluster.this.name
    }
  )

  lifecycle {
    ignore_changes = [
      paused, # Allow users to manage the paused state
    ]
  }
}
```
templates/ecs-job-template.tftpl
```
{
  "job_configuration": {
    "command": "{{ command }}",
    "env": "{{ env }}",
    "labels": "{{ labels }}",
    "name": "{{ name }}",
    "task_definition": {
      "containerDefinitions": [
        {
          "image": "{{ image }}",
          "name": "{{ container_name }}"
        }
      ],
      "cpu": "{{ cpu }}",
      "family": "{{ family }}",
      "memory": "{{ memory }}",
      "executionRoleArn": "{{ execution_role_arn }}"
    },
    "task_run_request": {
      "launchType": "{{ launch_type }}",
      "cluster": "${ecs_cluster}",
      "overrides": {
        "containerOverrides": [
          {
            "name": "{{ container_name }}",
            "command": "{{ command }}",
            "environment": "{{ env }}",
            "cpu": "{{ cpu }}",
            "memory": "{{ memory }}"
          }
        ],
        "cpu": "{{ cpu }}",
        "memory": "{{ memory }}",
        "taskRoleArn": "{{ task_role_arn }}"
      },
      "tags": "{{ labels }}",
      "taskDefinition": "{{ task_definition_arn }}",
      "capacityProviderStrategy": "{{ capacity_provider_strategy }}"
    },
    "configure_cloudwatch_logs": "{{ configure_cloudwatch_logs }}",
    "cloudwatch_logs_options": "{{ cloudwatch_logs_options }}",
    "cloudwatch_logs_prefix": "{{ cloudwatch_logs_prefix }}",
    "network_configuration": {
      "securityGroups": "{{ security_groups }}",
      "subnets": "{{ subnets }}"
    },
    "stream_output": "{{ stream_output }}",
    "task_start_timeout_seconds": "{{ task_start_timeout_seconds }}",
    "task_watch_poll_interval": "{{ task_watch_poll_interval }}",
    "auto_deregister_task_definition": "{{ auto_deregister_task_definition }}",
    "vpc_id": "${vpc_id}",
    "container_name": "{{ container_name }}",
    "cluster": "${ecs_cluster}",
    "match_latest_revision_in_family": "{{ match_latest_revision_in_family }}"
  },
  "variables": {
    "description": "Variables for templating an ECS job.",
    "type": "object",
    "properties": {
      "name": {
        "title": "Name",
        "description": "Name given to infrastructure created by a worker.",
        "type": "string"
      },
      "env": {
        "title": "Environment Variables",
        "description": "Environment variables to provide to the task run. These variables are set on the Prefect container at task runtime. These will not be set on the task definition.",
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      },
      "labels": {
        "title": "Labels",
        "description": "Labels applied to infrastructure created by a worker.",
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      },
      "command": {
        "title": "Command",
        "description": "The command to use when starting a flow run. In most cases, this should be left blank and the command will be automatically generated by the worker.",
        "type": "string"
      },
      "task_definition_arn": {
        "title": "Task Definition Arn",
        "description": "An identifier for an existing task definition to use. If set, options that require changes to the task definition will be ignored. All contents of the task definition in the job configuration will be ignored.",
        "type": "string"
      },
      "cluster": {
        "title": "Cluster",
        "description": "The ECS cluster to run the task in. An ARN or name may be provided. If not provided, the default cluster will be used.",
        "type": "string"
      },
      "family": {
        "title": "Family",
        "description": "A family for the task definition. If not provided, it will be inferred from the task definition. If the task definition does not have a family, the name will be generated. When flow and deployment metadata is available, the generated name will include their names. Values for this field will be slugified to match AWS character requirements.",
        "type": "string"
      },
      "launch_type": {
        "title": "Launch Type",
        "description": "The type of ECS task run infrastructure that should be used. Note that 'FARGATE_SPOT' is not a formal ECS launch type, but we will configure the proper capacity provider strategy if set here.",
        "default": "FARGATE",
        "enum": [
          "FARGATE",
          "EC2",
          "EXTERNAL",
          "FARGATE_SPOT"
        ],
        "type": "string"
      },
      "capacity_provider_strategy": {
        "title": "Capacity Provider Strategy",
        "description": "The capacity provider strategy to use when running the task. If a capacity provider strategy is specified, the selected launch type will be ignored.",
        "type": "array",
        "items": {
          "$ref": "#/definitions/CapacityProvider"
        }
      },
      "image": {
        "title": "Image",
        "description": "The image to use for the Prefect container in the task. If this value is not null, it will override the value in the task definition. This value defaults to a Prefect base image matching your local versions.",
        "type": "string"
      },
      "cpu": {
        "title": "CPU",
        "description": "The amount of CPU to provide to the ECS task. Valid amounts are specified in the AWS documentation. If not provided, a default value of 1024 will be used unless present on the task definition.",
        "type": "integer"
      },
      "memory": {
        "title": "Memory",
        "description": "The amount of memory to provide to the ECS task. Valid amounts are specified in the AWS documentation. If not provided, a default value of 2048 will be used unless present on the task definition.",
        "type": "integer"
      },
      "container_name": {
        "title": "Container Name",
        "description": "The name of the container flow run orchestration will occur in. If not specified, a default value of prefect will be used and if that is not found in the task definition the first container will be used.",
        "type": "string"
      },
      "task_role_arn": {
        "title": "Task Role ARN",
        "description": "A role to attach to the task run. This controls the permissions of the task while it is running.",
        "type": "string"
      },
      "execution_role_arn": {
        "title": "Execution Role ARN",
        "description": "An execution role to use for the task. This controls the permissions of the task when it is launching. If this value is not null, it will override the value in the task definition. An execution role must be provided to capture logs from the container.",
        "type": "string"
      },
      "configure_cloudwatch_logs": {
        "title": "Configure Cloudwatch Logs",
        "description": "If enabled, the Prefect container will be configured to send its output to the AWS CloudWatch logs service. This functionality requires an execution role with logs:CreateLogStream, logs:CreateLogGroup, and logs:PutLogEvents permissions. The default for this field is `False` unless `stream_output` is set.",
        "type": "boolean"
      },
      "cloudwatch_logs_options": {
        "title": "Cloudwatch Logs Options",
        "description": "When `configure_cloudwatch_logs` is enabled, this setting may be used to pass additional options to the CloudWatch logs configuration or override the default options. See the [AWS documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html#create_awslogs_logdriver_options) for available options. ",
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      },
      "cloudwatch_logs_prefix": {
        "title": "Cloudwatch Logs Prefix",
        "description": "When `configure_cloudwatch_logs` is enabled, this setting may be used to set a prefix for the log group. If not provided, the default prefix will be `prefect-logs_<work_pool_name>_<deployment_id>`. If `awslogs-stream-prefix` is present in `Cloudwatch logs options` this setting will be ignored.",
        "type": "string"
      },
      "subnets": {
        "title": "Overrides the subnets in the awsvpcConfiguration for the ECS task executing your workload. See the [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-awsvpcconfiguration.html) for available options.",
        "type": "array",
        "items": {
          "type": "string",
          "pattern": "^subnet-[a-f0-9]{8,17}$"
        },
        "minItems": 1,
        "default": ${default_subnets},
        "description": "List of subnet IDs in the VPC"
      },
      "security_groups": {
        "title": "Security Groups",
        "description": "Required with externally owned VPC's. Overrides the security group part of the ECS Worker's awsvpcConfiguration that defined in the ECS task executing your workload. See the [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-awsvpcconfiguration.html) for available options.",
        "type": "array",
        "additionalProperties": {
          "type": "string",
          "pattern": "^sg-[a-f0-9]{8,17}$"
        },
        "minItems": 1
      },
      "stream_output": {
        "title": "Stream Output",
        "description": "If enabled, logs will be streamed from the Prefect container to the local console. Unless you have configured AWS CloudWatch logs manually on your task definition, this requires the same prerequisites outlined in `configure_cloudwatch_logs`.",
        "type": "boolean"
      },
      "task_start_timeout_seconds": {
        "title": "Task Start Timeout Seconds",
        "description": "The amount of time to watch for the start of the ECS task before marking it as failed. The task must enter a RUNNING state to be considered started.",
        "default": 300,
        "type": "integer"
      },
      "task_watch_poll_interval": {
        "title": "Task Watch Poll Interval",
        "description": "The amount of time to wait between AWS API calls while monitoring the state of an ECS task.",
        "default": 5.0,
        "type": "number"
      },
      "auto_deregister_task_definition": {
        "title": "Auto Deregister Task Definition",
        "description": "If enabled, any task definitions that are created by this block will be deregistered. Existing task definitions linked by ARN will never be deregistered. Deregistering a task definition does not remove it from your AWS account, instead it will be marked as INACTIVE.",
        "default": false,
        "type": "boolean"
      },
      "match_latest_revision_in_family": {
        "title": "Match Latest Revision In Family",
        "description": "If enabled, the most recent active revision in the task definition family will be compared against the desired ECS task configuration. If they are equal, the existing task definition will be used instead of registering a new one. If no family is specified the default family \"prefect\" will be used.",
        "default": false,
        "type": "boolean"
      }
    },
    "required": [
      "subnets",
      "security_groups",
      "task_role_arn",
      "execution_role_arn"
    ],
    "definitions": {
      "CapacityProvider": {
        "title": "CapacityProvider",
        "description": "The capacity provider strategy to use when running the task.",
        "type": "object",
        "properties": {
          "capacityProvider": {
            "title": "Capacityprovider",
            "type": "string"
          },
          "weight": {
            "title": "Weight",
            "type": "integer"
          },
          "base": {
            "title": "Base",
            "type": "integer"
          }
        },
        "required": [
          "capacityProvider",
          "weight",
          "base"
        ]
      }
    }
  }
}
```

### Actual Behavior

```
╷
│ Error: Provider produced inconsistent result after apply
│ When applying changes to
│ module.example.prefect_work_pool.sandbox_prefect2_ecs, provider
│ "provider[\"registry.terraform.io/prefecthq/prefect\"]" produced an
│ unexpected new value: .base_job_template: was cty.StringVal("{\n
... <lots of output here>
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

Aimee McManus should be able to provide you access to the full output in slack

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Using prefect self hosted

### References

* #0000

### PR DESCRIPTION
**Pull request by mitchnielsen**
## Summary

- Addresses the "inconsistent values" error the provider would sometimes return when working with work pools that specify a base job template (context: https://github.com/PrefectHQ/terraform-provider-prefect/issues/244#issuecomment-2305902561)
- Adds `base_job_template` to the Work Pool tests
- Conforms to the newer, simpler method of unmarshaling the base job template that we use in our Block data logic

More information on each change is available in the relevant commit message.

Closes https://github.com/PrefectHQ/terraform-provider-prefect/issues/244

### CODE REVIEW

File: internal/provider/resources/work_pool.go [hunk 1]
```diff
@@ -6,6 +6,8 @@ import (
 	"fmt"
 	"strings"
 
+	"github.com/nsf/jsondiff"
```
Comment (mitchnielsen) [inline internal/provider/resources/work_pool.go:9]: [This package](https://github.com/nsf/jsondiff) only has a couple hundred stars, but it gave us the ability to return the differences in the output so we don't have to return the entire lengthy base job templates which is tough to debug (more detail in https://github.com/PrefectHQ/terraform-provider-prefect/pull/249/commits/9f67474fbc35cf4034b0d1f0f21bbadf693f2316).

If we prefer, we can go back to [google/go-cmp](https://github.com/google/go-cmp) which has several thousand stars and is better maintained. (This just means reverting to https://github.com/PrefectHQ/terraform-provider-prefect/pull/249/commits/810013f8d47a8807b3c6001e643b54b2ddca7375)

File: internal/provider/resources/work_pool.go [hunk 2]
```diff
@@ -434,3 +401,31 @@ func (r *WorkPoolResource) ImportState(ctx context.Context, req resource.ImportS
 		resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
 	}
 }
+
+// BaseJobTemplatesMatch checks to see if two base_job_template objects are
+// equivalent, accounting for differences in the order of the contents.
+//
+//nolint:ireturn // required by Terraform API
+func BaseJobTemplatesMatch(bjtPlan, bjtReceived map[string]interface{}) diag.Diagnostic {
```
Comment (mitchnielsen) [inline internal/provider/resources/work_pool.go:409]: - This function is exported because I needed to use it in the work pool tests to tell it how to accurately compare the fields.
- This got me thinking that it may be worth making this function more generic (i.e. not specific to base job templates) so we can use it to compare objects elsewhere in the provider. Open to doing that now or in a future PR (if we keep this setup, see earlier comment).

File: internal/provider/resources/work_pool.go [hunk 3]
```diff
@@ -434,3 +401,31 @@ func (r *WorkPoolResource) ImportState(ctx context.Context, req resource.ImportS
...
+		return helpers.SerializeDataErrorDiagnostic("base_job_template", "Work Pool base job template", err)
+	}
+
+	opts := jsondiff.DefaultJSONOptions()
+	differenceType, differences := jsondiff.Compare(bjtPlanBytes, bjtReceivedBytes, &opts)
+	if differenceType != jsondiff.FullMatch {
+		return diag.NewAttributeErrorDiagnostic(
+			path.Root("base_job_template"),
+			"Unexpected difference between base_job_template",
+			fmt.Sprintf("Expected the provided base_job_template to be equal to the one retrieved from the API, differences: %s", differences),
```
Comment (mitchnielsen) [inline internal/provider/resources/work_pool.go:426]: There's an example of what this looks like in the commit message for https://github.com/PrefectHQ/terraform-provider-prefect/pull/249/commits/9f67474fbc35cf4034b0d1f0f21bbadf693f2316.

File: internal/provider/resources/work_pool_test.go [hunk 4]
```diff
@@ -201,3 +229,59 @@ func getWorkPoolImportStateID(workPoolResourceName string, workspaceResourceName
 		return fmt.Sprintf("%s,%s", workspaceID, workPoolName), nil
 	}
 }
+
+var baseJobTemplateTpl = `
+{
+  "job_configuration": {
```
Comment (mitchnielsen) [inline internal/provider/resources/work_pool_test.go:235]: I grabbed this from our docs, as we need a fully-functional payload otherwise the API will throw an error.

File: internal/provider/resources/work_pool.go (hunk 1 above)
Comment (mitchnielsen) [reply internal/provider/resources/work_pool.go:9]: Going to give https://github.com/go-test/deep a try tomorrow.

Comment (mitchnielsen) [reply internal/provider/resources/work_pool.go]: This worked out better. Pushed 2d627e538bb5cc94732c418a593a0904c70e7c62

File: internal/provider/resources/work_pool.go (hunk 2 above)
Comment (mitchnielsen) [reply internal/provider/resources/work_pool.go]: With `go-test/deep`, the function was flexible enough that I moved it into the helpers package.

File: internal/provider/helpers/compare.go [hunk 5]
```diff
@@ -0,0 +1,14 @@
+package helpers
+
+import "github.com/go-test/deep"
+
+// ObjectsEqual checks to see if two  objects are equivalent, accounting for
```
Comment (parkedwards) [inline internal/provider/helpers/compare.go:5]:
```suggestion
// ObjectsEqual checks to see if two objects are equivalent, accounting for
```

File: internal/provider/resources/work_pool.go [hunk 6]
```diff
@@ -356,11 +309,30 @@ func (r *WorkPoolResource) Update(ctx context.Context, req resource.UpdateReques
 		return
 	}
 
-	resp.Diagnostics.Append(copyWorkPoolToModel(ctx, pool, &plan)...)
-	if resp.Diagnostics.HasError() {
+	// If the base job template from the retrieved work pool is equal
+	// to the base job template from the plan (taking into account that the
+	// fields could be in a different order), then we will use the plan's definition
+	// of the base job template in the state. This avoids "inconsistent value"
```
Comment (parkedwards) [inline internal/provider/resources/work_pool.go:315]: smart

**Review by parkedwards — APPROVED** [review]
